//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_2020.Class
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public DataProvider DP { get; set; }

        public KhachHang()
        {
            this.BDS = new HashSet<BD>();
            this.LichSuGiaoDiches = new HashSet<LichSuGiaoDich>();
            this.LichSuXems = new HashSet<LichSuXem>();
            DP = new DataProvider();
        }
    
        public string MaKH { get; set; }
        private string tenKH;
        public string TenKH {
            get
            {
                return tenKH;
            }
            set
            {
                if(tenKH != null)
                {
                    var customer = DP.Database.KhachHangs.SingleOrDefault(p => p.MaKH == this.MaKH);
                    customer.tenKH = value;
                    DP.Database.SaveChanges();
                }
                tenKH = value;
            }
        }
        private string diaChi;
        public string DiaChi {
            get
            {
                return diaChi;
            }
            set
            {
                if (diaChi != null)
                {
                    var customer = DP.Database.KhachHangs.SingleOrDefault(p => p.MaKH == this.MaKH);
                    customer.diaChi = value;
                    DP.Database.SaveChanges();
                }
                diaChi = value;
            }
        }
        private Nullable<decimal> sDT;
        public Nullable<decimal> SDT {
            get
            {
                return sDT;
            }
            set
            {
                if (sDT != null)
                {
                    var customer = DP.Database.KhachHangs.SingleOrDefault(p => p.MaKH == this.MaKH);
                    customer.sDT = value;
                    DP.Database.SaveChanges();
                }
                sDT = value;
            }
        }

        private string maChiNhanh;
        public string MaChiNhanh {
            get
            {
                return maChiNhanh;
            }
            set
            {
                if (maChiNhanh != null)
                {
                    var branch = DP.Database.ChiNhanhs.SingleOrDefault(p => p.MaChiNhanh == value && p.DeleteStatus == false);
                    if (branch == null)
                    {
                        MessageBox.Show("Không tồn tại mã chi nhánh đã nhập");
                        return;
                    }
                    var customer = DP.Database.KhachHangs.SingleOrDefault(p => p.MaKH == this.MaKH);
                    customer.maChiNhanh = value;
                    DP.Database.SaveChanges();
                }
                maChiNhanh = value;
            }
        }
        private string maNV;
        public string MaNV {
            get
            {
                return maNV;
            }
            set
            {
                if (maNV != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == value && p.DeleteStatus == false);
                    if (staff == null)
                    {
                        MessageBox.Show("Không tồn tại mã nhân viên đã nhập");
                        return;
                    }
                    var customer = DP.Database.KhachHangs.SingleOrDefault(p => p.MaKH == this.MaKH);
                    customer.maNV = value;
                    DP.Database.SaveChanges();
                }
                maNV = value;
            }
        }
        public Nullable<bool> DeleteStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD> BDS { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXem> LichSuXems { get; set; }
    }
}
