//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_2020.Class
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows;

    public partial class LichSuGiaoDich
    {
        public DataProvider DP { get; set; }

        public LichSuGiaoDich()
        {
            DP = new DataProvider();
        }

        public string MaKH { get; set; }
        public string MaNha { get; set; }
        public string MaCN { get; set; }
        public System.DateTime NgayGD { get; set; }
        
        public string LoaiGD { get; set; }
        private int soThangThue;
        public int SoThangThue {
            get
            {
                return soThangThue;
            }
            set
            {
                if(soThangThue != 0)
                {
                    if(value <= 0)
                    {
                        MessageBox.Show("Số tháng thuê phải lớn hơn 0");
                        return;
                    }
                    var dealHistory = DP.Database.LichSuGiaoDiches.SingleOrDefault(p => p.LoaiGD == "THUE" && p.MaKH == this.MaKH && p.MaCN == this.MaCN && p.MaNha == this.MaNha && p.NgayGD == this.NgayGD);
                    dealHistory.soThangThue = value;
                    DP.Database.SaveChanges();
                }
                
                soThangThue = value;
            }
        }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual BD BD { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
