//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_2020.Class
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows;
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public DataProvider DP { get; set; }

        public NhanVien()
        {
            this.BDS = new HashSet<BD>();
            this.KhachHangs = new HashSet<KhachHang>();
            DP = new DataProvider();
        }
    
        public string MaNV { get; set; }
        private string maChiNhanh;
        public string MaChiNhanh
        {
            get
            {
                return maChiNhanh;
            }
            set
            {
                if (maChiNhanh != null)
                {
                    var branch = DP.Database.ChiNhanhs.SingleOrDefault(p => p.MaChiNhanh == value && p.DeleteStatus == false);
                    if (branch == null)
                    {
                        MessageBox.Show("Không tồn tại mã chi nhánh đã nhập");
                        return;
                    }
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV== this.MaNV);
                    staff.maChiNhanh = value;
                    DP.Database.SaveChanges();
                }
                maChiNhanh = value;
            }
        }
        private string tenNV;
        public string TenNV {
            get
            {
                return tenNV;
            }
            set
            {
                if (tenNV != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.tenNV = value;
                    DP.Database.SaveChanges();
                }
                tenNV = value;
            }
        }
        private string diaChi;
        public string DiaChi {
            get
            {
                return diaChi;
            }
            set
            {
                if (diaChi != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.diaChi = value;
                    DP.Database.SaveChanges();
                }
                diaChi = value;
            }
        }
        private string sDT;
        public string SDT {
            get
            {
                return sDT;
            }
            set
            {
                if (sDT != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.sDT = value;
                    DP.Database.SaveChanges();
                }
                sDT = value;
            }
        }
        private string gioiTinh;
        public string GioiTinh {
            get
            {
                return gioiTinh;
            }
            set
            {
                if (gioiTinh != null)
                {
                    if(value != "NAM" && value != "NU")
                    {
                        MessageBox.Show("Giới tính phải là 'NAM' hoặc 'NU'");
                        return;
                    }
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.gioiTinh = value;
                    DP.Database.SaveChanges();
                }
                gioiTinh = value;
            }
        }
        private Nullable<System.DateTime> ngaySinh;
        public Nullable<System.DateTime> NgaySinh {
            get
            {
                return ngaySinh;
            }
            set
            {
                if (ngaySinh != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.ngaySinh = value;
                    DP.Database.SaveChanges();
                }
                ngaySinh = value;
            }
        }
        private Nullable<int> luong;
        public Nullable<int> Luong {
            get
            {
                return luong;
            }
            set
            {
                if (luong != null)
                {
                    var staff = DP.Database.NhanViens.SingleOrDefault(p => p.MaNV == this.MaNV);
                    staff.luong = value;
                    DP.Database.SaveChanges();
                }
                luong = value;
            }
        }
        public Nullable<bool> DeleteStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BD> BDS { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
