//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_2020.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class BD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BD()
        {
            this.LichSuGiaoDiches = new HashSet<LichSuGiaoDich>();
            this.LichSuXems = new HashSet<LichSuXem>();
        }
    
        public string MaNha { get; set; }
        public string MaCN { get; set; }
        public string NhaBan_Thue { get; set; }
        public string MaNV { get; set; }
        public string MaChiNhanh { get; set; }
        public Nullable<decimal> GiaBan_GiaThue { get; set; }
        public string DieuKien { get; set; }
        public string Duong { get; set; }
        public string Quan { get; set; }
        public string TP { get; set; }
        public string KhuVuc { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> SoPhong { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayHetHang { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiNha LoaiNha { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaoDich> LichSuGiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXem> LichSuXems { get; set; }
    }
}
