//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDS_2020.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaoDich
    {
        public string MaKH { get; set; }
        public string MaNha { get; set; }
        public string MaCN { get; set; }
        public System.DateTime NgayGD { get; set; }
        public string LoaiGD { get; set; }
        public int SoThangThue { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual BD BD { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
